In [1]:
# import libraries/packages
import numpy as np
import pandas as pd

In [2]:
# import and view dataset
df = pd.read_csv('MSCI_esg.csv').set_index('Company Name')
df.head()

,Ticker,Country,Sector,Subsector,Overall ESG RATING,Overall ESG SCORE,Environmental SCORE,Social SCORE,Governance SCORE
Company Name,,,,,,,,,
0921706 BC LTD,NaN,CA,Telecommunication Services,Wireless Telecommunication Services,A,6.6,10.0,7.4,2.7
1 MADISON OFFICE FEE LLC,NaN,US,Real Estate Management & Services,Office REITs,BBB,4.7,8.5,5.8,2.6
1&1 AG,1U1,DE,Telecommunication Services,Wireless Telecommunication Services,B,2.0,7.8,3.3,4.4
"1-800-FLOWERSCOM, INC",FLWS,US,Retail - Consumer Discretionary,Internet & Direct Marketing Retail,BBB,5.6,1.2,6.7,3.8
"1000 AUAHI, LLC",NaN,US,Real Estate Development & Diversified Activities,Real Estate Development,A,6.8,6.1,4.1,6.9

In [3]:
# describe dataset size
df.shape

(15646, 9)

In [4]:
# search for null values

for column in df.columns:
    print(f"Column {column} has {df[column].isnull().sum()} null values")

Column Ticker has 5205 null values
Column Country has 2 null values
Column Sector has 0 null values
Column Subsector has 786 null values
Column Overall ESG RATING has 0 null values
Column Overall ESG SCORE has 0 null values
Column Environmental SCORE has 0 null values
Column Social SCORE has 0 null values
Column Governance SCORE has 0 null values

In [5]:
df.nunique()

Ticker                 9195
Country                 108
Sector                   69
Subsector               159
Overall ESG RATING        7
Overall ESG SCORE       117
Environmental SCORE     101
Social SCORE            101
Governance SCORE         88
dtype: int64

In [6]:
# drop Ticker column 

df = df.drop(['Ticker'], axis=1, inplace=False)

In [7]:
# define the columns, ensuring 'Ticker' is dropped
df.columns

Index(['Country', 'Sector', 'Subsector', 'Overall ESG RATING',
       'Overall ESG SCORE', 'Environmental SCORE', 'Social SCORE',
       'Governance SCORE'],
      dtype='object')

In [8]:
df.head()

,Country,Sector,Subsector,Overall ESG RATING,Overall ESG SCORE,Environmental SCORE,Social SCORE,Governance SCORE
Company Name,,,,,,,,
0921706 BC LTD,CA,Telecommunication Services,Wireless Telecommunication Services,A,6.6,10.0,7.4,2.7
1 MADISON OFFICE FEE LLC,US,Real Estate Management & Services,Office REITs,BBB,4.7,8.5,5.8,2.6
1&1 AG,DE,Telecommunication Services,Wireless Telecommunication Services,B,2.0,7.8,3.3,4.4
"1-800-FLOWERSCOM, INC",US,Retail - Consumer Discretionary,Internet & Direct Marketing Retail,BBB,5.6,1.2,6.7,3.8
"1000 AUAHI, LLC",US,Real Estate Development & Diversified Activities,Real Estate Development,A,6.8,6.1,4.1,6.9

In [9]:
#determine unique ESG ratings

df['Overall ESG RATING'].unique()

array(['A', 'BBB', 'B', 'BB', 'AA', 'AAA', 'CCC'], dtype=object)

In [10]:
# determine score ranges in the dataset
df.describe()

       Overall ESG SCORE  Environmental SCORE  Social SCORE  Governance SCORE
count       15646.000000         15646.000000  15646.000000      15646.000000
mean            5.143982             5.315371      4.617442          4.789908
std             2.333359             2.407642      1.591180          1.592997
min             0.000000             0.000000      0.000000          0.000000
25%             3.400000             3.500000      3.600000          3.800000
50%             5.300000             5.200000      4.600000          5.000000
75%             7.000000             7.000000      5.600000          6.000000
max            10.000000            10.000000     10.000000          9.800000

In [11]:
# export to new csv
df.to_csv('clean_MSCI_esg.csv', encoding='utf-8')